name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run linter
        run: |
          poetry run black --check .

      - name: Run script
        run: |
          poetry run llm-context-builder --help
          poetry run llm-context-builder file .
          poetry run llm-context-builder --tokenizer naive file .
          poetry run llm-context-builder --tokenizer tiktoken file .
          poetry run llm-context-builder --tokenizer gemini --tokenizer-model gemini-1.5-flash-latest file .
          poetry run llm-context-builder --tokenizer transformers --tokenizer-model Xenova/Meta-Llama-3.1-Tokenizer file .
