name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run linter
        run: |
          uv run black --check .

      - name: Run script
        run: |
          uv run llm-context-builder --help
          uv run llm-context-builder file .
          uv run llm-context-builder --tokenizer naive file .
          uv run llm-context-builder --tokenizer tiktoken file .
          uv run llm-context-builder --tokenizer gemini --tokenizer-model gemini-1.5-flash-latest file .
          uv run llm-context-builder --tokenizer transformers --tokenizer-model Xenova/Meta-Llama-3.1-Tokenizer file .
